-   repo: https://github.com/pre-commit/pre-commit
    sha: v1.0.1
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.3
    hooks:
    -   id: autopep8-wrapper
    -   id: check-added-large-files
        exclude: (angular.js)
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: flake8
        exclude: (.*migrations.*|000*.py )
        args:
        - --max-line-length=200
    -   id: trailing-whitespace
    -   id: name-tests-test
        exclude: (.*migrations.*|migrations/0001_initial.py)
        args:
        - --max-line-length=200
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/pre-commit/mirrors-pylint
    sha: v1.7.2
    hooks:
    -   id: pylint
        exclude: (\.py$)
